jdbc:
  driverClassName: org.h2.Driver
  url: jdbc:h2:file:/data/linkhub;DB_CLOSE_DELAY=-1

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: create

spring:
  datasource:
    url: jdbc:h2:mem:linkhubdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
