create table link (id int generated by default as identity (start with 1) primary key,
                    name varchar(20) not null,
                    url varchar(255) not null,
                    createdAt timestamp);
